### ISSUE TITLE
Bring back the SVG code

### ISSUE THREAD

**Issue by schwa** [schwa/SwiftGraphics#17]

**Comment by rhcad** [comment]
The function CGPathFromSVGPath(string) is simple and practical relative to the importation SVG file, please help to review #60.
Thanks!

**Comment by rhcad** [comment]
I recommend to bring back the SVG code in **another** project. It may be too complicated to merge SVG importation feature in SwiftGraphics project.

I have used **SVGKit** and SwiftGraphics to import SVG files in [a branch of ShapeAnimation](https://github.com/rhcad/ShapeAnimation-Swift/tree/SVG), but there are some issues for some SVG files. So, there are more choices if you bring back it.

Look forward to your miracle. Thanks!
