### ISSUE TITLE
Distinguish between degrees and radians in APIs

### ISSUE THREAD

**Issue by garnett** [schwa/SwiftGraphics#31]
I am looking at the code
```swift
public init(center:CGPoint, size:CGSize, rotation:CGFloat = 0.0) {
...
        var rotation = rotation
        if size.height > size.width {
            rotation = DegreesToRadians(90)
        }
...
    }
```

From the source it's clear that deegress should be passed to ```rotation```. But even if there will be a doc (does somebody read them?) nothing prevents me from passing radians here.
Maybe it's be more clear if 2 new types will be introduced? degrees/radians (it can be made pretty lightweight with the help of typealiases, this won't prevent logic errors but the code will be more self-documented).

**Comment by schwa** [comment]
The code follows the usual computer convention of "radians everywhere". Degrees should only be used when translating angles for humans.

I played around with the two types method and didn't find anything I liked.  Feel free to submit a pull request if you come up with something you like
