### ISSUE TITLE
Line Terminology

### ISSUE THREAD

**Issue by schwa** [schwa/SwiftGraphics#55]
(from https://github.com/schwa/SwiftGraphics/commit/7d4c4ef0df0b5b5043b136bb60ba558963c7650b#commitcomment-9635993)

> Beeline is infinite line which passes two points.
> Rayline is infinite line which starts from a point and passes another point.
>
> Although both rayline and beeline can be converted to line segments, they can be used to draw guild lines and calculate intersection between lines and circles.
>
> I have implemented some functions about drawing, hittesting and calculating intersection with line segment, rayline, beeline and circle. They can be used in SwiftGraphics or another Swift project if needed.")

In traditional computer graphics we have lines and lines have start and end points. Lines of infinite length do not generally exist because they're either not useful or can be represented by very long lines.

In geometry we have lines (which are infinitely long) and line segments (a line between two points). (wikipedia has a good summary: https://en.wikipedia.org/wiki/Line_(geometry))

(On top of this we have a line path - which is an array of line segments where the end of the first line is the start of the next)

Currently I've been going with the geometry based terminology but in a practical usage I think we should refer to line segments as line and lines as something else (ray? infinite line?)

Beeline is merely a different representation of a line (and probably the most useful representation). I do think the terminology is confusing though - beeline does not seem to be a standard term.

**Comment by rhcad** [comment]
I used 'ray-line' and 'beeline' in many apps to draw auxiliary line or guide line such as angle bisector and parallel lines. 'beeline' is 'line' in theory, but many people assume that 'line' is 'line segment', so I use 'beeline' anyway to avoid confusion.

One solution is store subtype in LineSegment structure, but it will waste in LineChain.

For two point 'start' and 'end', I draw 'rayline' as  `let v=end-start; stroke(start, end+v*1e4)` and draw 'beeline' as `let v=(end-start)*1e4; stroke(start-v, end+v)`.

**Comment by rhcad** [comment]
Can we use 'InfiniteLine' instead of 'Beeline' or 'Line'? We can store type in InfiniteLine to represent 'ray-line', so there is not waste in LineChain.

**Comment by rhcad** [comment]
I noticed the TODO comment in `CGPoint+Trigonometry.swift`:

```
    // TODO: This should be identical to atan2() and it isn't!
    func angleTo(vec:CGPoint) -> CGFloat {       // [-M_PI, M_PI)
        return atan2(crossProduct(self, vec), dotProduct(self, vec))
    }
```

We can add the following comment if you agree:

```
    // Returns the angle between this vector and another vector 'vec'.
    // The result sign indicates the rotation direction from this vector to 'vec': positive for counter-clockwise, negative for clockwise.
    func angleTo(vec:CGPoint) -> CGFloat {       // [-M_PI, M_PI)
        return atan2(crossProduct(self, vec), dotProduct(self, vec))
    }
```
