### ISSUE TITLE
Swift 1.2 not available on Travis

### ISSUE THREAD

**Issue by schwa** [schwa/SwiftGraphics#58]
Unit tests can/will break on Travis CI due to Travis not supporting Swift 1.2

There's nothing we can do about this unfortunately. Travis won't support 1.2 because Xcode 6.3 is still under beta and is NDAed

**Comment by eneko** [comment]
Xcode 6.3 is no longer in beta, what is the status for having Swift 1.2 support?

**Comment by TAKeanice** [comment]
Any new information?

**Comment by schwa** [comment]
Travis CI still doesn't support 1.2

**Comment by schwa** [comment]
Fixed!

http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability/

**Comment by TAKeanice** [comment]
Cool!
